---
# Webservers
- hosts: webserver
  gather_facts: yes

  vars:
    services:
      - apache2
      - mysql
      #- beanstalkd
  vars_files:
    - ../app/config/parameters.yml.dist
  roles:
    # Start any services prior
    - { role: services, tags: ['services'] }
    # Deploy our application
    - { role: symfony2 }

    # Example of a daemon
    #- { role: daemonize, daemonize_gid: "{{http_user}}", daemonize_uid: "{{http_user}}", daemonize_command: '{{ symfony2_release_destination }}/app/console transdoc:worker:start -e {{symfony2_project_env}} -q', daemonize_script_name: transdoc-worker }
