---
apache_packages: [apache2, apache2-utils]
php_enable_apc: false

php_use_managed_ini: false

php_opcache_enabled_in_ini: true

php_max_execution_time: 120
php_cli_max_execution_time: -1
php_memory_limit: 1G
php_cli_memory_limit: -1

php_enable_php_fpm: true
apache_remove_default_vhost: true

apache_mods_enabled:
  - status.load
  - rewrite.load
