---
apache_packages: [apache2, apache2-mpm-prefork, apache2-utils]
php_enable_apc: false

php_conf_path: "{{ '/etc/php5/fpm' if php_enable_php_fpm else '/etc/php5/apache2' }}"
php_extension_conf_path: "{{ php_conf_path }}/conf.d"
php_use_managed_ini: false

php_enable_php_fpm: true
php_max_execution_time: 1200
php_cli_max_execution_time: -1
php_memory_limit: 1G

