---
# Are we storing our cache elsewhere? e.g. Vagrant setups
- name: Delete the original cache directory
  file: state=absent path="{{symfony2_release_destination}}/app/cache" force="yes"
  when: symfony2_project_cache_location is defined

- name: Create the alternative cache directory
  sudo: yes
  file: state=directory path={{symfony2_project_cache_location}}/{{symfony2_project_name}}/{{symfony2_project_release}} owner={{ansible_ssh_user}} group={{http_user}}
  when: symfony2_project_cache_location is defined

- name: Link the alternative cache directory
  file: state=link src="{{symfony2_project_cache_location}}/{{symfony2_project_name}}/{{symfony2_project_release}}" path="{{symfony2_release_destination}}/app/cache" force="yes"
  when: symfony2_project_cache_location is defined

# Are we storing our logs elsewhere? e.g. Vagrant setups
- name: Delete the original log directory
  file: state=absent path="{{symfony2_release_destination}}/app/logs" force="yes"
  when: symfony2_project_log_location is defined

- name: Create the alternative log directory
  sudo: yes
  file: state=directory path={{symfony2_project_log_location}}/{{symfony2_project_name}}/{{symfony2_project_release}} owner={{ansible_ssh_user}} group={{http_user}}
  when: symfony2_project_log_location is defined

- name: Link the alternative log directory
  file: state=link src="{{symfony2_project_log_location}}/{{symfony2_project_name}}/{{symfony2_project_release}}" path="{{symfony2_release_destination}}/app/logs" force="yes"
  when: symfony2_project_log_location is defined