---
# Work out the HTTP user
- name: Discover HTTP user
  shell: "ps axo user:50,pid,cmd | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d' ' -f1"
  register: http_user_command
  tags:
    - always

- set_fact: http_user="{{http_user_command.stdout}}"
  tags:
    - always

- name: Add user to www-data group
  sudo: yes
  user: name="{{ ansible_ssh_user }}" groups="www-data" append="yes"
  when: not skip_permissions
