---
- local_action: shell cd {{symfony2_project_source}} && git fetch -t && git describe --abbrev=0 --tags
  register: current_version_command
  sudo: yes
  ignore_errors: yes
  tags:
    - always

- set_fact: symfony2_project_release="{{current_version_command.stdout}}"
  when: "current_version_command.rc == 0"
  tags:
    - always

- set_fact: symfony2_release_destination="{{symfony2_project_root}}/releases/{{symfony2_project_release}}"
  tags:
    - always

# Create the directories
- name: Create the root directory.
  sudo: yes
  file: state=directory owner={{ansible_ssh_user}} group={{http_user}} path={{symfony2_project_root}}

- name: Create the shared directory.
  file: state=directory owner={{ansible_ssh_user}} group={{http_user}} path={{symfony2_project_root}}/shared

- name: Create the shared/app/config directory.
  file: state=directory path={{symfony2_project_root}}/shared/app/config

- name: Create the shared/web/uploads directory.
  file: state=directory path={{symfony2_project_root}}/shared/web/uploads

- name: Create the release {{symfony2_project_release}} directory.
  file: state=directory path={{symfony2_release_destination}}

#- name: Reset any non-git files
#  local_action: shell cd {{symfony2_project_source}} && git reset --hard HEAD && git clean -e vendor -ffdx
#  when: symfony2_project_source is defined

- name: Sync the source code to the destination
  synchronize: src={{symfony2_project_source}} dest={{symfony2_release_destination}} archive=yes owner=no
  when: symfony2_project_source is defined

- name: Pull sources from the repository.
  git: repo={{symfony2_project_repo}} dest={{symfony2_release_destination}} version={{symfony2_project_branch}} key_file=/root/.ssh/deployment_id_rsa accept_hostkey=yes
  when: symfony2_project_repo is defined and ssh_deployment_key is defined

- name: Create symlink for app/config/parameters.yml from shared directory
  file: state=link src={{symfony2_project_root}}/shared/app/config/parameters.yml dest={{symfony2_release_destination}}/app/config/parameters.yml force=yes

- name: Copy tenants from old host
  command: "cp {{symfony2_project_root}}/current/app/config/config_tenant* {{symfony2_release_destination}}/app/config/"

- name: Create web/uploads symlink
  file: state=link src={{symfony2_project_root}}/shared/web/uploads path={{symfony2_release_destination}}/web/uploads force=yes
