daemonize_respawn_limit: '5 10'

daemonize_start_on: 'started mysql'
daemonize_stop_on: 'stopped mysql'

daemonize_bin: '{{symfony2_php_path}}'
daemonize_bin_opts: '{{symfony2_console_path}}'

daemonize_opts: '-e {{symfony2_project_env}}'

daemonize_gid: "{{http_user|default('www-data')}}"
daemonize_uid: "{{ansible_ssh_user|default('www-data')}}"
