---
#- name: Create RDS instance
#  rds: >
#    command=create
#    instance_name="{{ mysql_users|first().name }}"
#    db_engine=MySQL
#    size="{{ rds_database_size }}"
#    instance_type="{{ rds_instance_type }}"
#    username="{{ mysql_users|first().name }}"
#    password="{{ mysql_users|first().password }}"
#
## Get facts about an instance
#- rds: >
#    command=facts
#    instance_name="{{ mysql_databases|first().name }}"
#    register: database_facts

- name: Install MySQL PIP
  pip: name="MySQL-python"

- name: Ensure MySQL databases are present.
  mysql_db: >
    name="{{ item.name }}"
    collation="{{ item.collation | default('utf8_general_ci') }}"
    encoding="{{ item.encoding | default('utf8') }}"
    login_host="{{ override_parameters.database_host|default(parameters.database_host) }}"
    login_user="{{ mysql_root_username }}"
    login_password="{{ mysql_root_password }}"
    state=present
  with_items: mysql_databases

- name: Ensure MySQL users are present.
  mysql_user: >
    name="{{ item.name }}"
    host="{{ item.host | default('localhost') }}"
    login_host="{{ override_parameters.database_host|default(parameters.database_host)}}"
    login_user="{{ mysql_root_username }}"
    login_password="{{ mysql_root_password }}"
    password="{{ item.password }}"
    priv="{{ item.priv | default('*.*:USAGE') }}"
    state=present
  with_items: mysql_users
