---
# Database server
- hosts: dbserver
  vars:
    services:
      - mysql
  roles:
    # Start any services prior
    - { role: services, tags: ['services'] }

# Search server
- hosts: search
  tasks:
    - shell: service elasticsearch start
      sudo: yes
      tags: ['services'] 
    
# Webservers
- hosts: webserver
  gather_facts: yes
  max_fail_percentage: 0
  vars:
    services:
      - php5-fpm
      - apache2
      #- beanstalkd
  vars_files:
    - ../app/config/parameters.yml.dist
    - vars/mysql.yml
  roles:
    # Start any services prior
    - { role: services, tags: ['services'] }
    # Deploy our application
    - { role: symfony2 }

    # Example of a daemon
    #- { role: daemonize, daemonize_command: 'transdoc:callbacks:start', daemonize_script_name: transdoc-callback, tags: ['services'] }
