---
# Database server
- hosts: dbserver
  vars:
    services:
      - mysql
  roles:
    # Start any services prior
    - { role: services, tags: ['services'] }

# Search server
- hosts: search
  tasks:
    - shell: service elasticsearch start
      sudo: yes
      tags: ['services'] 
    - name: Wait for elastic search to boot
      wait_for: port=9200 timeout=60
      tags: ['services']
    
# Webservers
- hosts: webserver
  gather_facts: yes
  max_fail_percentage: 0
  vars:
    services:
      - apache2
  vars_files:
    - ../app/config/parameters.yml.dist
    - vars/mysql.yml
    - vars/symfony.yml
    - vars/packages.yml
    - vars/apache.yml
  roles:
    # Start FPM prior
    - { role: services, tags: ['services'], services: ['php5-fpm'], when: "'php5-fpm' in php_packages" }
    # Start Beanstalk prior
    - { role: services, tags: ['services'], services: ['beanstalkd'], when: "'beanstalkd' in system_packages" }
    # Start any other services prior
    - { role: services, tags: ['services'] }
    
    # Deploy our application
    - { role: symfony2 }

    # Example of a daemon
    #- { role: daemonize, daemonize_command: 'transdoc:callbacks:start', daemonize_script_name: transdoc-callback, tags: ['services'] }
