---
# Database server
- hosts: dbserver
  vars:
    services:
      - mysql
  roles:
    # Start any services prior
    - { role: services, tags: ['services'] }

# Search server
- hosts: search
  vars:
    services:
      - elasticsearch
  roles:
    # Start any services prior
    - { role: services, tags: ['services'] }

# Webservers
- hosts: webserver
  gather_facts: yes
  vars:
    services:
      - apache2
      #- beanstalkd
  vars_files:
    - ../app/config/parameters.yml.dist
  roles:
    # Start any services prior
    - { role: services, tags: ['services'] }
    # Deploy our application
    - { role: symfony2 }

    # Example of a daemon
    #- { role: daemonize, daemonize_command: 'transdoc:callbacks:start', daemonize_script_name: transdoc-callback, tags: ['services'] }
